FROM openjdk:11-jre

ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/mi/myservice.jar"]

# Add Maven dependencies (not shaded into the artifact; Docker-cached)
ADD target/lib           /usr/share/myservice/lib
# Add the service itself
ARG JAR_FILE
ADD target/${JAR_FILE} /usr/share/myservice/myservice.jar